<?php
/**
 * @file
 * Defines basic functionality common to all parts of Acro CRM.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function acrocrm_help($path, $arg) {
  switch ($path) {
    case "admin/help#acrocrm":
      return '<p>' . t("Establishes basic functionality for all parts of Acro CRM") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function acrocrm_menu() {
  $items = array();

  // Menu items that are basically just menu blocks.
  $items['acrocrm'] = array(
    'title' => 'CRM Home',
    'description' => 'Acro CRM',
    'weight' => -8,
    'page callback' => 'acrocrm_landing_page',
    'access arguments' => array('access acrocrm'),
    'file' => 'includes/acrocrm.admin.inc',
  );
  $items['admin/structure/acrocrm'] = array(
    'title' => 'Acro CRM',
    'description' => 'Administer Acro CRM items, such as team members, contacts, etc.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer acrocrm'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/acrocrm'] = array(
    'title' => 'Acro CRM',
    'description' => 'Settings for Acro modules.',
    'position' => 'right',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/acrocrm/crm'] = array(
    'title' => 'Acro CRM settings',
    'description' => 'Configure Acro CRM.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('acrocrm_settings'),
    'access arguments' => array('administer acrocrm'),
    'file' => 'includes/acrocrm.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function acrocrm_permission() {
  return array(
    'administer acrocrm' => array(
      'title' => t('Administer Acro CRM'),
      'description' => t('Perform administration tasks for my Acro CRM.'),
    ),
    'access acrocrm' => array(
      'title' => t('Access Acro CRM'),
      'description' => t('Access Acro CRM.'),
    ),
    'sales rep' => array(
      'title' => t('Sales Representative'),
      'description' => t('A person who is part of the sales division.'),
    ),
  );
}

// TODO: as we talked about, you can probably slim this down or even drop it entirely.
/**
 * Implements hook_theme().
 */
function acrocrm_theme() {
  return array(
    'acrocrm_property_field' => array(
      'variables' => array(
        'label_hidden' => FALSE,
        'title_attributes' => NULL,
        'label' => '',
        'content_attributes' => NULL,
        'items' => array(),
        'item_attributes' => array(0 => ''),
        'classes' => '',
        'attributes' => '',
      ),
    ),
    'page__acrocrm' => array(
      'variables' => array('page' => NULL),
      'preprocess functions' => array('acrocrm_page'),
    ),
    'acrocrm_home' => array(
      'base hook' => 'page__acrocrm',
      'path' => drupal_get_path('module', 'acrocrm') . '/templates',
      'template' => 'main--acrocrm',
    ),
  );
}

/**
 * These are things that will appear on every page.
 *
 * @param $variables
 */
function acrocrm_page(&$variables) {
  $page = $variables['page'];
  $module_path = drupal_get_path('module', 'acrocrm');
  $css_path = $module_path . '/templates/assets/css/';
  $js_path = $module_path . '/templates/assets/js/';

  // css for header
  drupal_add_css($css_path . 'acrocrm_reset.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'bootstrap.min.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'metismenu.min.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'timeline.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'sb-admin-2.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'font-awesome.min.css', array('group' => CSS_THEME));
  drupal_add_css($css_path . 'acrocrm.css', array('group' => CSS_THEME));

  // js for header
  drupal_add_js('var $ = jQuery;', 'inline', array('group' => JS_THEME));
  drupal_add_js($js_path . 'bootstrap.min.js', array('group' => JS_THEME));
  drupal_add_js($js_path . 'sb-admin-2.js', array('group' => JS_THEME));
  drupal_add_js($js_path . 'metismenu.min.js', array('group' => JS_THEME));

  // js for footer
  drupal_add_js('http://code.jquery.com/ui/1.11.4/jquery-ui.js', 'external', array('scope' => 'footer'));
  drupal_add_js($js_path . 'acrocrm.js', array('scope' => 'footer'));

  // Add items to sidebar
  if (module_exists('acrocrm_leads')) {
    $items['leads'] = array(
      'path' => '#',
      'title' => t('Leads'),
      'permission' => 'administer acrocrm',
      'child_pages' => array(
        'overview' => array(
          'path' => '/acrocrm_leads/overview',
          'title' => t('Overview'),
          'permission' => 'administer acrocrm',),
        'new_lead' => array(
          'path' => '/acrocrm_leads/new_lead',
          'title' => t('New Lead'),
          'permission' => 'administer acrocrm',),
      ),
    );
  }
  $items['settings'] = array(
    'path' => 'admin/config/acrocrm',
    'title' => t('Settings'),
    //'description' => t('Acro CRM configuration and settings.'),
    'permission' => 'administer acrocrm',
  );


  foreach ($items as $key => $item) {
    if ((isset($item['module']) && !module_exists($item['module'])) || !user_access($item['permission'])) {
      unset($items[$key]);
    }
  }

  $markup = '';
  foreach ($items as $item) {
    $markup .= '<li><a href="' . $item['path'] . '"><i class="fa fa-fw"></i>' . $item['title'];
    if (array_key_exists('child_pages', $item)) {
      $markup .= '<span class="fa arrow"></span></a>'
        . '<ul class="nav nav-second-level">';
      foreach ($item['child_pages'] as $child_item) {
        $markup .= '<li>'
          . '<a href = "' . $child_item['path'] . '" >' . $child_item['title'] . '</a >'
          . '</li >';
      }
      $markup .= '</ul>';
    } else {
      $markup .= '</a>';
    }

    $markup .= '</li>';
  }

  $page['sidebar_first']['links'] = array(
    '#type' => 'markup',
    '#markup' => $markup,
  );

  $variables['page'] = $page;
}

//function acrocrm_js_alter(&$javascript) {
//  // Swap out jQuery to use an updated version of the library.
//  $javascript['misc/jquery.js']['data'] = drupal_get_path('module', 'acrocrm') . '/misc/jquery-2.1.4.min.js';
//}


//TODO - you don't need to do this, having menu items under /admin/ is usually sufficient to have it get pulled into the menu
//this hook comes from a contrib module so it adds an unnecessary dependency
/**
 * Implements hook_admin_menu_output_build().
 *
 * Add Acro CRM to the admin menu.
 */
function acrocrm_admin_menu_output_build(&$content) {
  // Load menu builder functions.
  module_load_include('inc', 'admin_menu');
  // Because it isn't assigned an explicit menu, the 'acrocrm' menu item is
  // added to the 'navigation' menu by default. However, in case it has been
  // moved to a different menu, query to find the menu name.
  if ($menu_name = db_query("SELECT menu_name FROM {menu_links} WHERE router_path = 'acrocrm'")->fetchField()) {
    $items = admin_menu_links_menu(admin_menu_tree($menu_name));//menu_output_build
    if (isset($items['acrocrm'])) {
      // Peg position to that of the admin/people menu item.
      if (isset($content['menu']['admin/people'])) {
        $items['acrocrm']['#weight'] = $content['menu']['admin/people']['#weight'];
      }
      // Change title from "CRM Dashboard". No need for t() here because it's a
      // product name.
      $items['acrocrm']['#title'] = 'Acro CRM';
      $content['menu']['acrocrm'] = $items['acrocrm'];
    }
  }
}

//TODO - if you just specify your stuff under admin/* then you don't need to do this
/**
 * Implements hook_admin_paths().
 */
function acrocrm_admin_paths() {
  // Set Acro CRM admin paths based on configuration.
  if (variable_get('acrocrm_admin_path', FALSE)) {
    $paths = array(
      'acrocrm' => TRUE,
      'acrocrm/*' => TRUE,
    );
    return $paths;
  }
}
