<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param $path
 *  Path of the site to display help
 * @param $arg
 *  Array that holds the current path returned by the arg() function.
 * @return string
 *  Ant HTML string
 */
function acrocrm_dashboard_help($path, $arg) {
  switch ($path) {
    case "admin/help#acrocrm_dashboard":
      return '<p>' . t("Dashboard module for AcroCRM") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu
 */
function acrocrm_dashboard_menu() {
  $items = array();

  $items['acrocrm_dashboard'] = array(
    'title' => 'AcroCRM Dashboard',
    'description' => 'AcroCRM Dashboard',
    'page callback' => 'acrocrm_dashboard_main_page',
    'access arguments' => array('access acrocrm'),
  );

  return $items;
}
function acrocrm_dashboard_theme() {
  return array(
    'page__acrocrm_dashboard' => array(
      'variables' => array('page' => NULL),
      'preprocess functions' => array('acrocrm_dashboard_page'),
    ),
    'acrocrm_dashboard_home' => array(
      'base hook' => 'page__acrocrm_dashboard',
      'path' => drupal_get_path('module', 'acrocrm') . '/templates',
      'template' => 'main--acrocrm',
    ),
  );
}

function acrocrm_dashboard_page(&$variables) {
  acrocrm_page($variables);
  $js_path = drupal_get_path('module', 'acrocrm') . '/templates/assets/js/';
  drupal_add_js($js_path . 'jquery.flot.js', array('scope' => 'footer'));
  drupal_add_js($js_path . 'jquery.flot.pie.js', array('scope' => 'footer'));
  drupal_add_js($js_path . 'jquery.flot.resize.js', array('scope' => 'footer'));
  drupal_add_js($js_path . 'jquery.flot.tooltip.min.js', array('scope' => 'footer'));
  drupal_add_js($js_path . 'acrocrm_charts.js', array('scope' => 'footer'));
}

function acrocrm_dashboard_main_page() {
  $page['content']['header'] = array(
    '#markup' => '<div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">' . t('Dashboard') . '</h1>
                    </div>
                  </div>'
  );
  $lead_count = getLeadCounts(date('Y-m-d', strtotime('-7 days')), date('Y-m-d', strtotime('+1 days')));
  $page['content']['notifications'] = array(
    '#markup' => '<div class="row">
                    <div class="col-lg-12">
                      <div class="panel panel-info">
                          <div class="panel-heading"><h4>' . t('Lead Conversion: ') . date('F j', strtotime('-7 days')) . ' - ' . date('F j') . '</h4></div>
                          <div class="panel-body">
                             <div class="col-lg-4">
                                <div class="panel panel-grey">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-exclamation-circle fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge">' . $lead_count['uncommitted'] . '</div>
                                                <div>' . t('Uncommitted') . '</div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="panel panel-green">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-check-circle fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge">' . $lead_count['committed'] . '</div>
                                                <div>' . t('Committed') . '</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="panel panel-red">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-times-circle fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge">' . $lead_count['deleted'] . '</div>
                                                <div>' . t('Deleted') . '</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          </div>
                          <a href="' . base_path() . 'acrocrm_leads/overview' . '">
                              <div class="panel-footer">
                                  <span class="pull-left">' . t('View Details') . '</span>
                                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                  <div class="clearfix"></div>
                              </div>
                          </a>
                      </div>
                  </div>
                </div> <!-- / .row --->

                <div class="row">
                  <div class="col-md-6">
                    <div class="panel panel-warning">
                        <div class="panel-heading"><h4>' . t('Sales Representatives') . '</h4></div>
                        <div class="panel-body">'
                            . getSalesReps() .
                        '</div>
                        <a href="' . base_path() . 'admin/people' . '">
                            <div class="panel-footer">
                                <span class="pull-left">' . t('View Details') . '</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="panel panel-warning">
                        <div class="panel-heading"><h4>' . t('Lead Assignment: ') . date('F j', strtotime('-7 days')) . ' - ' . date('F j') . '</h4></div>
                        <div class="panel-body">'
                          . getLeadAssignment(date('Y-m-d', strtotime('-7 days')), date('Y-m-d', strtotime('+1 days'))) .
                          '<div class="flot-chart">
                            <div class="flot-chart-content" id="flot-pie-chart"></div>
                          </div>
                        </div>
                        <a href="' . base_path() . 'acrocrm_leads/overview' . '">
                            <div class="panel-footer">
                                <span class="pull-left">' . t('View Details') . '</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                  </div>
                </div> <!-- / .row -->'

  );
  return theme('acrocrm_dashboard_home', array('page' => $page));
}

/**
 *
 * Gets the counts for the number of uncommitted, deleted, and committed leads
 *
 * @param $start_date
 *  Start date of range to search
 * @param $end_date
 *  End date of range to search
 * @return array
 *  Array mapping the counts of each lead type
 */
function getLeadCounts($start_date, $end_date) {
  $query = db_select('leads', 'l');
  $query->fields('l');
  $query->condition('created_time', $start_date, '>=');
  $query->condition('created_time', $end_date, '<=');
  $query = $query->execute();

  $lead_count = array(
    'uncommitted' => 0,
    'deleted' => 0,
    'committed' => 0
  );

  if ($query->rowCount() > 0) {
    while ($lead = $query->fetchAssoc()) {
      if ($lead['status'] == 'UNCOMMITTED') {
        $lead_count['uncommitted'] = $lead_count['uncommitted'] + 1;
      }
      else if ($lead['status'] == 'DELETED') {
        $lead_count['deleted'] = $lead_count['deleted'] + 1;
      }
      else if ($lead['status'] == 'COMMITTED') {
        $lead_count['committed'] = $lead_count['committed'] + 1;
      }
    }
  }
  return $lead_count;
}

/**
 *
 * Generate a list of sales reps names and email address
 *
 * @return String
 *  List of leads to be printed in sales rep panel
 */
function getSalesReps() {
  $users = entity_load('user');
  $sales_reps = '';

  foreach ($users as $user) {
    if (user_access('sales rep', $user) && $user->uid>1) {
      $sales_reps .= '<p><strong>' . $user->name . '</strong> ' . $user->mail . '</p>';
    }
  }
  return $sales_reps;
}

/**
 *
 * Find the number of leads assigned to each sales rep over the last week
 *
 * @param $start_date
 *  Start date of range to search
 * @param $end_date
 *  End date of range to search
 * @return String
 *  div with info about counts of each sales rep to be used by charts library
 * to make sales rep count chart
 */
function getLeadAssignment($start_date, $end_date) {
  $query = db_select('assigned_leads', 'al');
  $query->fields('al');
  $query->addExpression('COUNT(al.lead_id)', 'count');
  $query->innerJoin('leads', 'l', 'al.lead_id = l.lead_id');
  $query->innerJoin('users', 'u', 'al.uid = u.uid');
  $query->fields('u');
  $query->condition('created_time', $start_date, '>=');
  $query->condition('created_time', $end_date, '<=');
  $query->groupBy('al.uid');
  $query = $query->execute();

  $rep_counts = '<div id="rep-chart-info">';
  $lead_sum = 0;
  if ($query->rowCount() > 0) {
    while ($result = $query->fetchAssoc()) {
      $lead_sum += $result['count'];
      $rep_counts .= '<span class="chart-data" data-repname="' . $result['name'] .'" data-repid="' . $result['uid'] . '" data-repcount="' . $result['count'] . '"></span>';
    }
  }

  $rep_counts .= '<span id="leads-total" data-lead-total="' . $lead_sum .'"></span></div>';

  return $rep_counts;
}